import Link from "next/link";
import { ArrowRight, BadgeCheck, Building2, CarFront, FileSearch, MapPin, ShieldCheck, Wrench } from "lucide-react";
const services=[
{icon:<ShieldCheck/>,title:"Vistoria Cautelar",text:"Análise técnica de identificação, estrutura, pintura e histórico para decisões mais seguras."},
{icon:<FileSearch/>,title:"Pesquisa Veicular",text:"Consulta completa de bases estaduais e nacionais, leilão, sinistro, restrições e muito mais."},
{icon:<Wrench/>,title:"Inspeção Completa",text:"Avaliação cautelar combinada com análise mecânica e diagnóstico eletrônico do veículo."},
{icon:<CarFront/>,title:"Car Hunter",text:"Acompanhamento técnico para localizar, avaliar e apoiar a compra do veículo ideal."},
{icon:<Building2/>,title:"Soluções para Empresas",text:"Operação sob medida para concessionárias, revendas, leilões, bancos e seguradoras."},
{icon:<MapPin/>,title:"Atendimento In Loco",text:"Equipe móvel para inspeções no local, em Porto Alegre, Região Metropolitana e demais regiões do RS."}];
export default function Home(){return <main>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">Engenharia automotiva aplicada</div><h1>Inspeções veiculares com tecnologia, precisão e segurança.</h1><p>Laudos técnicos, pesquisa veicular e soluções digitais para particulares, lojistas, concessionárias e empresas do setor automotivo.</p><div className="hero-actions"><Link className="btn btn-primary" href="/agendamento">Solicitar vistoria <ArrowRight size={18}/></Link><Link className="btn btn-light" href="/consulta-classe-a">Consulta Classe A</Link><a className="btn btn-light" href="https://laudos.visaoclassea.com.br">Consultar laudo</a></div></div><div className="hero-card"><BadgeCheck size={42}/><strong>Confiança respaldada por engenharia</strong><p>Equipe qualificada, procedimentos padronizados e responsável técnico para laudos emitidos com rigor e rastreabilidade.</p></div></div></section>
<div className="quickbar"><div className="container quickbar-grid"><div className="quickitem">Engenheiro responsável</div><div className="quickitem">Atendimento em todo RS</div><div className="quickitem">Vistoria móvel In Loco</div><div className="quickitem">Laudos 100% digitais</div></div></div>
<section className="section"><div className="container"><div className="section-head"><div className="eyebrow">Nossos serviços</div><h2>Soluções completas para avaliar veículos com segurança</h2><p>Da vistoria individual à operação em grande volume, a Visão Classe A combina experiência técnica e tecnologia própria.</p></div><div className="grid-3">{services.map((s)=><article className="card" key={s.title}><div className="icon">{s.icon}</div><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></div></section>
<section className="section soft"><div className="container"><div className="section-head"><div className="eyebrow">Estrutura e escala</div><h2>Uma operação preparada para crescer com seus parceiros</h2></div><div className="stats"><div className="stat"><strong>+3 anos</strong>de mercado</div><div className="stat"><strong>320+</strong>vistorias por mês</div><div className="stat"><strong>22+ anos</strong>de experiência técnica</div><div className="stat"><strong>RS</strong>cobertura estadual</div></div></div></section>
<section className="section"><div className="container"><div className="cta"><div><div className="eyebrow">Precisa avaliar um veículo?</div><h2>Agende sua vistoria com uma equipe técnica especializada.</h2></div><Link className="btn btn-primary" href="/agendamento">Agendar agora <ArrowRight size={18}/></Link></div></div></section>
</main>}
